#!/bin/sh
desktops() {

ws1="I"
ws2="II"
ws3="III"
ws4="IV"
ws5="V"
ws6="VI"
ws7="VII"
ws8="VIII"
ws9="IX"
ws10="X"

# Unoccupied
un="0"

# check if Occupied
o1=$(bspc query -D -d .occupied --names | grep "^$ws1$" )
o2=$(bspc query -D -d .occupied --names | grep "^$ws2$" )
o3=$(bspc query -D -d .occupied --names | grep "^$ws3$" )
o4=$(bspc query -D -d .occupied --names | grep "^$ws4$" )
o5=$(bspc query -D -d .occupied --names | grep "^$ws5$" )
o6=$(bspc query -D -d .occupied --names | grep "^$ws6$" )
o7=$(bspc query -D -d .occupied --names | grep "^$ws7$" )
o8=$(bspc query -D -d .occupied --names | grep "^$ws8$" )
o9=$(bspc query -D -d .occupied --names | grep "^$ws9$" )
o10=$(bspc query -D -d .occupied --names | grep "^$ws10$" )

# check if Focused

if [ $(bspc query -D -d focused --names | grep "^$ws1$" ) ]; then
    f1="F"
else
    f1=""
fi
if [ $(bspc query -D -d focused --names | grep "^$ws2$" ) ]; then
    f2="F"
else
    f2=""
fi
if [ $(bspc query -D -d focused --names | grep "^$ws3$" ) ]; then
    f3="F"
else
    f3=""
fi
if [ $(bspc query -D -d focused --names | grep "^$ws4$" ) ]; then
    f4="F"
else
    f4=""
fi
if [ $(bspc query -D -d focused --names | grep "^$ws5$" ) ]; then
    f5="F"
else
    f5=""
fi
if [ $(bspc query -D -d focused --names | grep "^$ws6$" ) ]; then
    f6="F"
else
    f6=""
fi
if [ $(bspc query -D -d focused --names | grep "^$ws7$" ) ]; then
    f7="F"
else
    f7=""
fi
if [ $(bspc query -D -d focused --names | grep "^$ws8$" ) ]; then
    f8="F"
else
    f8=""
fi
if [ $(bspc query -D -d focused --names | grep "^$ws9$" ) ]; then
    f9="F"
else
    f9=""
fi
if [ $(bspc query -D -d focused --names | grep "^$ws10$" ) ]; then
    f10="F"
else
    f10=""
fi

ic_1=""
ic_2=""
ic_3=""
ic_4=""
ic_5=""
ic_6=""
ic_7=""
ic_8=""
ic_9=""
ic_10=""

# Make the focused desktop a filled circle
if [ $f1 ]; then
    ic_1=""
elif [ $f2 ]; then
    ic_2=""
elif [ $f3 ]; then
    ic_3=""
elif [ $f4 ]; then
    ic_4=""
elif [ $f5 ]; then
    ic_5=""
elif [ $f6 ]; then
    ic_6=""
elif [ $f7 ]; then
    ic_7=""
elif [ $f8 ]; then
    ic_8=""
elif [ $f9 ]; then
    ic_9=""
elif [ $f10 ]; then
    ic_10=""
fi

# echo -e "(box :class \"desktops\" :orientation \"h\" :space-evenly false :valign \"center\" :halign \"center\" (button :onclick \"bspc desktop -f ^1\" :class \"$un$o1$f1\" \"$ic_1\") (button :onclick \"bspc desktop -f ^2\" :class \"$un$o2$f2\" \"$ic_2\") (button :onclick \"bspc desktop -f ^3\" :class \"$un$o3$f3\" \"$ic_3\") (button :onclick \"bspc desktop -f ^4\" :class \"$un$o4$f4\" \"$ic_4\") (button :onclick \"bspc desktop -f ^5\" :class \"$un$o5$f5\" \"$ic_5\") (button :onclick \"bspc desktop -f ^6\" :class \"$un$o6$f6\" \"$ic_6\") (button :onclick \"bspc desktop -f ^7\" :class \"$un$o7$f7\" \"$ic_7\") (button :onclick \"bspc desktop -f ^8\" :class \"$un$o8$f8\" \"$ic_8\") (button :onclick \"bspc desktop -f ^9\" :class \"$un$o9$f9\" \"$ic_9\") (button :onclick \"bspc desktop -f ^10\" :class \"$un$o10$f10\" \"$ic_10\"))"
echo -e "(box :class \"desktops\" :orientation \"h\" :space-evenly false (button :onclick \"bspc desktop -f ^1\" :class \"$un$o1$f1\" \"$ic_1\") (button :onclick \"bspc desktop -f ^2\" :class \"$un$o2$f2\" \"$ic_2\") (button :onclick \"bspc desktop -f ^3\" :class \"$un$o3$f3\" \"$ic_3\") (button :onclick \"bspc desktop -f ^4\" :class \"$un$o4$f4\" \"$ic_4\") (button :onclick \"bspc desktop -f ^5\" :class \"$un$o5$f5\" \"$ic_5\") (button :onclick \"bspc desktop -f ^6\" :class \"$un$o6$f6\" \"$ic_6\") (button :onclick \"bspc desktop -f ^7\" :class \"$un$o7$f7\" \"$ic_7\") (button :onclick \"bspc desktop -f ^8\" :class \"$un$o8$f8\" \"$ic_8\") (button :onclick \"bspc desktop -f ^9\" :class \"$un$o9$f9\" \"$ic_9\") (button :onclick \"bspc desktop -f ^10\" :class \"$un$o10$f10\" \"$ic_10\"))"

}

desktops
bspc subscribe desktop node_transfer | while read -r _ ; do
desktops
done
