# Shell variables
# Generated by 'wal'
wallpaper='/home/ryscith/Sync/Purple_KeyboardSwitch.png'

# Special
background='#1a1a1a'
foreground='#c5c5c5'
cursor='#c5c5c5'

# Colors
color0='#1a1a1a'
color1='#733f85'
color2='#634f72'
color3='#63817e'
color4='#eb6025'
color5='#8f9495'
color6='#88c4bd'
color7='#c5c5c5'
color8='#535353'
color9='#733f85'
color10='#634f72'
color11='#63817e'
color12='#eb6025'
color13='#8f9495'
color14='#88c4bd'
color15='#c5c5c5'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
