--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/ryscith/Sync/Purple_KeyboardSwitch.png"

-- Special
background="#1a1a1a"
foreground="#c5c5c5"
cursor="#c5c5c5"

-- Colors
color0="#1a1a1a"
color1="#733f85"
color2="#634f72"
color3="#63817e"
color4="#eb6025"
color5="#8f9495"
color6="#88c4bd"
color7="#c5c5c5"
color8="#535353"
color9="#733f85"
color10="#634f72"
color11="#63817e"
color12="#eb6025"
color13="#8f9495"
color14="#88c4bd"
color15="#c5c5c5"
