#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor DisplayPort-0 -d I II III IV V
bspc monitor DisplayPort-1 -d VI VII VIII IX X

bspc config border_width         2
bspc config window_gap           3

bspc config split_ratio           0.50
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config pointer_follows_focus false
bspc config focus_follows_pointer false

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a mplayer2 state=floating
bspc rule -a Emacs state=tiled
bspc rule -a Zathura state=tiled
bspc rule -a Spotify desktop='^4'

#############################################
### Colors

# Restore previous color theme
wal -R

# Source color theme
. "${HOME}/.cache/wal/colors.sh"

# Set the border colors.
bspc config normal_border_color "$color0"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color1"
bspc config presel_feedback_color "$color1"

#############################################
### Autostart

# Set display from arandr saved script
sh ~/.scripts/monitor.sh &
# Bar
~/.config/polybar/launch.sh &
# Notifications
~/.config/bspwm/scripts/launchdunst.sh &
# Polkit
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
# Wallpaper
nitrogen --restore &
# Dex
dex -a -s /etc/xdg/autostart/:~/.config/autostart/ &
# Picom
picom --experimental-backends &
# Network Applet
nm-applet --indicator &

#############################################
### System Settings

# Cursor
xsetroot -cursor_name left_ptr &
# Natural Scrolling
xinput set-prop 13 282 1 &
# Audio Devices Auto-Load When Connected 
pactl load-module module-switch-on-connect &
