#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor DisplayPort-0 -d I II III IV V
bspc monitor DisplayPort-1 -d VI VII VIII IX X

bspc config border_width         2
bspc config window_gap           3

bspc config split_ratio           0.50
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config pointer_follows_focus false
bspc config focus_follows_pointer false

bspc rule -a Emacs state=tiled
bspc rule -a Zathura state=tiled

#############################################
### Colors

# Set the border colors.
# Catppuccin mocha colors
bspc config normal_border_color "#313244"   #surface0
bspc config active_border_color "#89b4fa"   #blue
bspc config focused_border_color "#cba6f7"  #mauve
bspc config presel_feedback_color "#89b4fa" #blue

#############################################
### Autostart

# Set display from arandr saved script
sh ~/.screenlayout/dualmonitorsetup.sh &
# Bars
eww open toolbar &
eww open vert_monitor_toolbar &
# Notifications
~/.config/bspwm/scripts/launchdunst.sh &
# Polkit
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
# Wallpaper
nitrogen --restore &
# Dex
dex -a -s /etc/xdg/autostart/:~/.config/autostart/ &
# Picom
picom --experimental-backends &
# Network Applet
nm-applet --indicator &

#############################################
### System Settings

# Cursor
xsetroot -cursor_name left_ptr &
# Natural Scrolling
xinput set-prop 13 282 1 &
# Audio Devices Auto-Load When Connected 
pactl load-module module-switch-on-connect &
# Turn numlock on
numlockx &
